"""adding email_notifications table

Revision ID: 65b1af57cade
Revises: dae731137108
Create Date: 2025-08-17 11:20:37.687376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b1af57cade'
down_revision = 'dae731137108'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('recipients', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('cc', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('bcc', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('attachments', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('template_identifier', sa.String(length=255), nullable=True),
    sa.Column('is_direct_request', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_sent_successfully', sa.Boolean(), nullable=False),
    sa.Column('fail_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_notifications')
    # ### end Alembic commands ###
